rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  passport: ${RABBITMQ_PASSWORD:guest}
  virtualhost: ${RABBITMQ_VHOST:/}
  switch_flag: false
  pool_size: 10