spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost} # 你的虚拟机IP
    port: ${RABBITMQ_PORT:5672} # 端口
    virtual-host: ${RABBITMQ_VHOST:/pai_coding} # 虚拟主机
    username: ${RABBITMQ_USERNAME:guest} # 用户名
    password: ${RABBITMQ_PASSWORD:guest} # 密码
    

rabbitmq:
  switchFlag: false